export const ordersUiText = {
  listPage: {
    title: 'Orders List',
    createButton: 'Create Order',
    filtersTitle: 'Filters',
  },
  detailsPage: {
    title: 'Order Details',
    backToOrders: 'Orders',
    labels: {
      orderNumber: 'Order number',
      assignedManager: 'Assigned Manager',
      orderStatus: 'Order Status',
      totalPrice: 'Total Price',
      delivery: 'Delivery',
      createdOn: 'Created On',
      customerDetails: 'Customer Details',
      requestedProducts: 'Requested Products',
      deliveryInformation: 'Delivery Information',
      orderHistory: 'Order History',
      comments: 'Comments',
    },
    tabs: {
      delivery: 'Delivery',
      history: 'Order History',
      comments: 'Comments',
    },
    actions: {
      cancel: 'Cancel Order',
      process: 'Process Order',
      reopen: 'Reopen Order',
      refresh: 'Refresh Order',
      createComment: 'Create',
    },
    placeholders: {
      processNeedsDelivery: 'Add delivery before processing order',
      noDeliveryScheduled: 'Delivery is not scheduled yet',
      historyPlaceholder: 'Order history will be implemented in a separate iteration.',
      commentInput: 'Enter a comment',
      commentAuthorFallback: 'AQA User',
    },
    fields: {
      customer: {
        email: 'Email',
        name: 'Name',
        phone: 'Phone',
        country: 'Country',
        city: 'City',
        street: 'Street',
        house: 'House',
        flat: 'Flat',
        createdOn: 'Created On',
        notes: 'Notes',
      },
      delivery: {
        condition: 'Delivery Type',
        finalDate: 'Delivery Date',
        country: 'Country',
        city: 'City',
        street: 'Street',
        house: 'House',
        flat: 'Flat',
      },
    },
  },
  dialogs: {
    reopenTitle: 'Reopen Order',
    reopenConfirm: 'Yes, Reopen',
    cancel: 'Cancel',
    createOrderTitle: 'Create Order',
    createOrderCustomerLabel: 'Customer*',
    createOrderProductLabel: 'Product*',
    createOrderProductsTitle: 'Products',
    createOrderAddProductButton: 'Add Product',
    createOrderSubmitButton: 'Create',
    createOrderTotalPriceLabel: 'Total Price:',
    details: {
      cancelTitle: 'Cancel Order',
      cancelMessage: 'Are you sure you want to cancel the order?',
      cancelConfirm: 'Yes, Cancel',
      processTitle: 'Process Order',
      processMessage: 'Are you sure you want to process the order?',
      processConfirm: 'Yes, Process',
      reopenTitle: 'Reopen Order',
      reopenMessage: 'Are you sure you want to reopen the order?',
      reopenConfirm: 'Yes, Reopen',
      editCustomerTitle: 'Edit Customer',
      editCustomerSearchLabel: 'Customer*',
      editCustomerSearchPlaceholder: 'Search by name or email',
      editCustomerLoading: 'Loading customers...',
      editCustomerNoResults: 'No matching customers found.',
      editCustomerSave: 'Save',
      editProductsTitle: 'Edit Products',
      editProductsLabel: 'Products*',
      editProductsSearchLabel: 'Product*',
      editProductsSearchPlaceholder: 'Search by name or manufacturer',
      editProductsLoading: 'Loading products...',
      editProductsNoResults: 'No matching products found.',
      editProductsAdd: 'Add Product',
      editProductsSave: 'Save',
      editProductsSelectProduct: 'Select product',
      editProductsSelectRowHint: 'Select a product row to edit.',
      editProductsUnavailable: 'Unavailable product',
    },
  },
  toasts: {
    exportCompleted: 'Export completed',
    created: 'Order was successfully created',
    updated: 'Order was successfully updated',
    reopened: 'Order was successfully reopened',
    canceled: 'Order was successfully canceled',
    processed: 'Order processing was successfully started',
    commentCreated: 'Comment was successfully posted',
    commentDeleted: 'Comment was successfully deleted',
    notFoundRedirect: 'Order was not found. Redirecting to orders list.',
  },
  errors: {
    noCustomers: 'No customers found. Please add one before creating an order.',
    noProducts: 'No products found. Please add one before creating an order.',
    createUnavailable: 'Unable to create an order. Please try again later.',
    customersLoadFailed: 'Unable to load customers. Please try again later.',
    missingOrderId: 'Order id is missing.',
    orderNotFound: 'Order was not found.',
    detailsUnavailable: 'Unable to load order details. Please refresh the page.',
    updateCustomerFailed: 'Failed to update customer. Please try again later.',
    updateProductsFailed: 'Failed to update products. Please try again later.',
    orderNoLongerDraft: 'Order is no longer in Draft status. Page data was refreshed.',
    commentCreateFailed: 'Failed to post comment. Please try again later.',
    commentDeleteFailed: 'Failed to delete comment. Please try again later.',
  },
  validation: {
    commentsInvalid: 'Comment should be in range 1-250 and without < or > symbols',
  },
} as const

export function getReopenOrderMessage(orderId?: string) {
  return orderId
    ? `Are you sure you want to reopen order "${orderId}"?`
    : 'Are you sure you want to reopen this order?'
}
