export const ordersUiText = {
  listPage: {
    title: 'Orders List',
    createButton: 'Create Order',
    filtersTitle: 'Filters',
    emptyStateNoOrders: 'No orders created yet.',
  },
  detailsPage: {
    title: 'Order Details',
    backToOrders: 'Orders',
    labels: {
      orderNumber: 'Order number',
      assignedManager: 'Assigned Manager',
      orderStatus: 'Order Status',
      totalPrice: 'Total Price',
      delivery: 'Delivery',
      createdOn: 'Created On',
      customerDetails: 'Customer Details',
      requestedProducts: 'Requested Products',
      deliveryInformation: 'Delivery Information',
      deliveryAddress: 'Delivery Address',
      orderHistory: 'Order History',
      comments: 'Comments',
    },
    tabs: {
      delivery: 'Delivery',
      history: 'Order History',
      comments: 'Comments',
    },
    actions: {
      cancel: 'Cancel Order',
      process: 'Process Order',
      reopen: 'Reopen Order',
      receive: 'Receive',
      save: 'Save',
      scheduleDelivery: 'Schedule',
      editDelivery: 'Edit',
      saveDelivery: 'Save Delivery',
      cancelDeliveryEdit: 'Cancel',
      cancelReceive: 'Cancel',
      refresh: 'Refresh Order',
      createComment: 'Create',
    },
    history: {
      whatChanged: 'What changed',
      stateAfterEvent: 'State after action',
      productsAfterEvent: 'Products after action',
      orderStatus: 'Order status',
      totalPrice: 'Total price',
      delivery: 'Delivery',
      assignedManager: 'Assigned manager',
      previous: 'Previous',
      updated: 'Updated',
      notAssigned: 'Not assigned',
      notReceived: 'Not received',
      productLabel: 'Product',
      unknownActionLabel: 'Unknown action',
      fallbackChangeLabel: 'Action',
      noHistory: 'History is empty.',
    },
    placeholders: {
      processNeedsDelivery: 'Add delivery before processing order',
      noDeliveryScheduled: 'Delivery is not scheduled yet',
      noDelivery: 'Not Scheduled',
      selectManager: 'Click to select manager',
      deliveryAddressSourceCustomer: 'Customer address',
      deliveryAddressSourceStore: 'Store pickup address',
      deliveryAddressSourceCustom: 'Custom address',
      historyPlaceholder: 'Order history will be implemented in a separate iteration.',
      commentInput: 'Enter a comment',
      commentAuthorFallback: 'AQA User',
      selectAll: 'Select All',
      noComments: 'No comments yet.',
    },
    fields: {
      customer: {
        email: 'Email',
        name: 'Name',
        phone: 'Phone',
        country: 'Country',
        city: 'City',
        street: 'Street',
        house: 'House',
        flat: 'Flat',
        createdOn: 'Created On',
        notes: 'Notes',
      },
      delivery: {
        condition: 'Delivery Type',
        location: 'Location',
        finalDate: 'Delivery Date',
        country: 'Country',
        city: 'City',
        street: 'Street',
        house: 'House',
        flat: 'Flat',
      },
    },
  },
  dialogs: {
    reopenTitle: 'Reopen Order',
    reopenConfirm: 'Yes, Reopen',
    cancel: 'Cancel',
    createOrderTitle: 'Create Order',
    createOrderCustomerLabel: 'Customer*',
    createOrderProductLabel: 'Product*',
    createOrderProductsTitle: 'Products',
    createOrderAddProductButton: 'Add Product',
    createOrderSubmitButton: 'Create',
    createOrderTotalPriceLabel: 'Total Price:',
    details: {
      cancelTitle: 'Cancel Order',
      cancelMessage: 'Are you sure you want to cancel the order?',
      cancelConfirm: 'Yes, Cancel',
      processTitle: 'Process Order',
      processMessage: 'Are you sure you want to process the order?',
      processConfirm: 'Yes, Process',
      reopenTitle: 'Reopen Order',
      reopenMessage: 'Are you sure you want to reopen the order?',
      reopenConfirm: 'Yes, Reopen',
      editCustomerTitle: 'Edit Customer',
      editCustomerSearchLabel: 'Customer*',
      editCustomerSearchPlaceholder: 'Search by name or email',
      editCustomerLoading: 'Loading customers...',
      editCustomerNoResults: 'No matching customers found.',
      editCustomerSave: 'Save',
      assignManagerTitle: 'Assign Manager',
      editAssignedManagerTitle: 'Edit Assigned Manager',
      assignManagerSearchLabel: 'Manager*',
      assignManagerSearchPlaceholder: 'Search manager...',
      assignManagerLoading: 'Loading managers...',
      assignManagerNoResults: 'No matching managers found.',
      assignManagerSave: 'Save',
      unassignManagerTitle: 'Unassign Manager',
      unassignManagerMessage: 'Are you sure you want to unassign manager from this order?',
      unassignManagerConfirm: 'Yes, Unassign',
      editProductsTitle: 'Edit Products',
      editProductsLabel: 'Products*',
      editProductsSearchLabel: 'Product*',
      editProductsSearchPlaceholder: 'Search by name or manufacturer',
      editProductsLoading: 'Loading products...',
      editProductsNoResults: 'No matching products found.',
      editProductsAdd: 'Add Product',
      editProductsSave: 'Save',
      editProductsSelectProduct: 'Select product',
      editProductsSelectRowHint: 'Select a product row to edit.',
      editProductsUnavailable: 'Unavailable product',
      editProductsDiscardTitle: 'Discard Changes',
      editProductsDiscardMessage: 'You have unsaved product changes. Discard them?',
      editProductsDiscardConfirm: 'Discard',
      editProductsDiscardCancel: 'Keep Editing',
      editProductsDisabledReasonNoChanges: 'No changes to save.',
      editProductsDisabledReasonEmptyRows: 'Select a product for each row.',
      editProductsDisabledReasonUnavailable: 'Remove or replace unavailable products.',
      editProductsDisabledReasonCheckingAvailability: 'Checking product availability...',
    },
  },
  toasts: {
    exportCompleted: 'Export completed',
    created: 'Order was successfully created',
    updated: 'Order was successfully updated',
    deliverySaved: 'Delivery was successfully saved',
    reopened: 'Order was successfully reopened',
    canceled: 'Order was successfully canceled',
    processed: 'Order processing was successfully started',
    productsReceived: 'Products were successfully received',
    managerAssigned: 'Manager was successfully assigned to the order',
    managerUnassigned: 'Manager was successfully unassigned from the order',
    commentCreated: 'Comment was successfully posted',
    commentDeleted: 'Comment was successfully deleted',
    notFoundRedirect: 'Order was not found. Redirecting to orders list.',
  },
  errors: {
    noCustomers: 'No customers found. Please add one before creating an order.',
    noProducts: 'No products found. Please add one before creating an order.',
    createUnavailable: 'Unable to create an order. Please try again later.',
    customersLoadFailed: 'Unable to load customers. Please try again later.',
    missingOrderId: 'Order id is missing.',
    invalidOrderId: 'Order id is invalid.',
    orderNotFound: 'Order was not found.',
    detailsUnavailable: 'Unable to load order details. Please refresh the page.',
    updateCustomerFailed: 'Failed to update customer. Please try again later.',
    updateProductsFailed: 'Failed to update products. Please try again later.',
    orderNoLongerDraft: 'Order is no longer in Draft status. Page data was refreshed.',
    orderStateChanged: 'Order state has changed. Page data was refreshed.',
    deliverySaveFailed: 'Failed to save delivery. Please try again later.',
    receiveProductsFailed: 'Failed to receive products. Please try again later.',
    assignManagerFailed: 'Unable to assign manager. Please try again later.',
    unassignManagerFailed: 'Unable to unassign manager. Please try again later.',
    commentCreateFailed: 'Failed to post comment. Please try again later.',
    commentDeleteFailed: 'Failed to delete comment. Please try again later.',
  },
  validation: {
    commentsInvalid: 'Comment should be in range 1-250 and without < or > symbols',
    deliveryDateInvalid: 'Delivery date is required',
    deliveryCountryInvalid: 'Select a valid country',
    deliveryCityInvalid: "City's name should contain only 1-20 alphabetical characters and one space between",
    deliveryStreetInvalid: 'Street should contain only 1-40 alphanumerical characters and one space between',
    deliveryHouseInvalid: 'House number should be in range 1-999',
    deliveryFlatInvalid: 'Flat number should be in range 1-9999',
  },
} as const

export function getReopenOrderMessage(orderId?: string) {
  return orderId
    ? `Are you sure you want to reopen order "${orderId}"?`
    : 'Are you sure you want to reopen this order?'
}
