export const inventoryUiText = {
  listPage: {
    title: 'Inventory List',
    filtersTitle: 'Filters',
    filterSections: {
      inventoryStatus: 'Inventory Status',
      productStatus: 'Product Status',
      manufacturer: 'Manufacturer',
    },
    chips: {
      searchPrefix: 'Search',
      inventoryStatusPrefix: 'Inventory',
      productStatusPrefix: 'Product',
      manufacturerPrefix: 'Manufacturer',
    },
  },
  detailsPage: {
    backToInventory: 'Inventory',
    actions: {
      viewProduct: 'View Product',
      viewHistory: 'View History',
      adjust: 'Adjust',
      settings: 'Settings',
      cancel: 'Cancel',
      saveAdjustment: 'Save Adjustment',
      saveSettings: 'Save Settings',
    },
    summary: {
      inventoryStatus: 'Inventory Status',
      totalAvailable: 'Total Available',
      totalQuantity: 'Total Quantity',
      totalReserved: 'Total Reserved',
      lowStockVariants: 'Low Stock Variants',
      outOfStockVariants: 'Out Of Stock Variants',
    },
    labels: {
      variantStatus: 'Product Variant Status',
      stockGroup: 'Stock',
      rulesGroup: 'Rules',
      quantity: 'Quantity',
      reserved: 'Reserved',
      available: 'Available',
      threshold: 'Threshold',
      directOrder: 'Direct Order',
      stockStatus: 'Stock Status',
      sellingOutOfStock: 'Selling Out Of Stock',
      allowed: 'Allowed',
      blocked: 'Blocked',
      adjustTitle: 'Adjust Inventory',
      currentQuantity: 'Quantity',
      currentReserved: 'Reserved',
      currentAvailable: 'Available',
      adjustmentType: 'Adjustment Type',
      adjustmentAmount: 'Adjustment Amount',
      newQuantity: 'New Quantity',
      reason: 'Reason',
      comment: 'Comment',
      resultPreview: 'Result Preview',
      change: 'Change',
      commentLimit: 'Comment limit: 250 characters',
      settingsTitle: 'Variant Inventory Settings',
      lowStockThreshold: 'Low Stock Threshold',
      settingsPreview: 'Settings Preview',
      stockStatusAfterUpdate: 'Stock Status After Update',
    },
    placeholders: {
      missingProductId: 'Product id is missing.',
      unavailable: 'Inventory details are unavailable.',
      noVariants: 'No inventory variants found.',
      reason: 'Supplier delivery, correction...',
      comment: 'Optional manager comment',
    },
    validation: {
      quantityRequired: 'Enter a positive integer to preview the adjustment.',
      quantityNegative: 'Quantity cannot become negative.',
      quantityLowerThanReserved: 'Quantity cannot be lower than reserved amount.',
      commentTooLong: 'Comment cannot exceed 250 characters.',
      thresholdInvalid: 'Threshold must be an integer 0 or greater.',
    },
    toasts: {
      adjustmentSaved: 'Inventory was adjusted successfully.',
      settingsSaved: 'Variant settings were updated successfully.',
    },
  },
  historyPage: {
    title: 'Inventory History',
    backToDetails: 'Inventory',
    variantsTitle: 'Variants',
    variantsSubtitle: 'Select variant to scope history entries',
    allVariantsLabel: 'All variants',
    allVariantsMeta: 'Parent product history',
    metaTrailing: 'History for all product variants',
    filtersTitle: 'Filters',
    filterSections: {
      type: 'Adjustment Type',
      sortOrder: 'Sort',
    },
    sortOrder: {
      newestFirst: 'Newest first',
      oldestFirst: 'Oldest first',
    },
    orderIdLabel: 'Order ID',
    dateFromLabel: 'From Date',
    dateToLabel: 'To Date',
    chips: {
      variantPrefix: 'Variant',
      typePrefix: 'Type',
      orderIdPrefix: 'Order',
      fromDatePrefix: 'From',
      toDatePrefix: 'To',
      sortPrefix: 'Sort',
    },
    columns: {
      createdOn: 'Date',
      variant: 'Variant',
      type: 'Type',
      quantity: 'Quantity',
      reserved: 'Reserved',
      comment: 'Comment',
      manager: 'Manager',
      orderId: 'Order',
    },
    placeholders: {
      loadingFailed: 'Inventory history is unavailable.',
      noVariants: 'No variants found for this product.',
      noComment: '-',
      unknownManager: 'Unknown Manager',
      systemManager: 'System',
    },
  },
  reservationsPage: {
    title: 'Inventory Reservations',
    subtitle: 'Operational view of active inventory locks and processing reservations.',
    emptyStateNoReservations: 'No active reservations found',
    filtersTitle: 'Filters',
    filterSections: {
      type: 'Reservation Type',
      createdDate: 'Created Date',
      expiresBefore: 'Expires Before',
      sort: 'Sort',
    },
    fromDateLabel: 'From Date',
    toDateLabel: 'To Date',
    expiresBeforeLabel: 'Expires Before',
    sortLabel: 'Sort',
    actions: {
      openInventory: 'Open Inventory',
    },
    summary: {
      activeReservations: 'Active Reservations',
      expiringSoon: 'Expiring Soon',
      processing: 'Processing Locks',
      reservedUnits: 'Reserved Units',
    },
    chips: {
      searchPrefix: 'Search',
      typePrefix: 'Type',
      fromDatePrefix: 'From',
      toDatePrefix: 'To',
      expiresBeforePrefix: 'Expires before',
      sortPrefix: 'Sort',
    },
    card: {
      orderPrefix: 'Order #',
      reservedProductsTitle: 'Reserved Products',
      reservationDetailsTitle: 'Reservation Details',
      customerLabel: 'Customer:',
      createdLabel: 'Created:',
      updatedLabel: 'Updated:',
      expiresAtLabel: 'Expires At:',
      noExpiration: 'Active until delivery',
      reservedQuantityLabel: 'Reserved:',
      openOrder: 'Open Order',
      unknownCustomer: 'Unknown Customer',
      unknownVariant: '-',
    },
    placeholders: {
      loadingFailed: 'Inventory reservations are unavailable.',
    },
  },
} as const
