export const inventoryUiText = {
  listPage: {
    title: 'Inventory List',
    filtersTitle: 'Filters',
    filterSections: {
      inventoryStatus: 'Inventory Status',
      productStatus: 'Product Status',
      manufacturer: 'Manufacturer',
    },
    chips: {
      searchPrefix: 'Search',
      inventoryStatusPrefix: 'Inventory',
      productStatusPrefix: 'Product',
      manufacturerPrefix: 'Manufacturer',
    },
  },
  detailsPage: {
    backToInventory: 'Inventory',
    actions: {
      viewProduct: 'View Product',
      adjust: 'Adjust',
      settings: 'Settings',
      cancel: 'Cancel',
      saveAdjustment: 'Save Adjustment',
      saveSettings: 'Save Settings',
    },
    summary: {
      inventoryStatus: 'Inventory Status',
      totalAvailable: 'Total Available',
      totalQuantity: 'Total Quantity',
      totalReserved: 'Total Reserved',
      lowStockVariants: 'Low Stock Variants',
      outOfStockVariants: 'Out Of Stock Variants',
    },
    labels: {
      variantStatus: 'Product Variant Status',
      stockGroup: 'Stock',
      rulesGroup: 'Rules',
      quantity: 'Quantity',
      reserved: 'Reserved',
      available: 'Available',
      threshold: 'Threshold',
      directOrder: 'Direct Order',
      stockStatus: 'Stock Status',
      sellingOutOfStock: 'Selling Out Of Stock',
      allowed: 'Allowed',
      blocked: 'Blocked',
      adjustTitle: 'Adjust Inventory',
      currentQuantity: 'Quantity',
      currentReserved: 'Reserved',
      currentAvailable: 'Available',
      adjustmentType: 'Adjustment Type',
      adjustmentAmount: 'Adjustment Amount',
      newQuantity: 'New Quantity',
      reason: 'Reason',
      comment: 'Comment',
      resultPreview: 'Result Preview',
      change: 'Change',
      commentLimit: 'Comment limit: 250 characters',
      settingsTitle: 'Variant Inventory Settings',
      lowStockThreshold: 'Low Stock Threshold',
      settingsPreview: 'Settings Preview',
      stockStatusAfterUpdate: 'Stock Status After Update',
    },
    placeholders: {
      missingProductId: 'Product id is missing.',
      unavailable: 'Inventory details are unavailable.',
      noVariants: 'No inventory variants found.',
      reason: 'Supplier delivery, correction, damaged item...',
      comment: 'Optional manager comment',
    },
    validation: {
      quantityRequired: 'Enter a positive integer to preview the adjustment.',
      quantityNegative: 'Quantity cannot become negative.',
      quantityLowerThanReserved: 'Quantity cannot be lower than reserved amount.',
      commentTooLong: 'Comment cannot exceed 250 characters.',
      thresholdInvalid: 'Threshold must be an integer 0 or greater.',
    },
    toasts: {
      adjustmentSaved: 'Inventory was adjusted successfully.',
      settingsSaved: 'Variant settings were updated successfully.',
    },
  },
} as const
