export const ORDER_DETAILS_PRODUCT_SEARCH_LIMIT = 10
export const ORDER_DETAILS_SEARCH_DEBOUNCE_MS = 300
export const ORDER_DETAILS_DELIVERY_MIN_DATE_OFFSET_DAYS = 3
export const ORDER_DETAILS_DELIVERY_MAX_DATE_OFFSET_DAYS = 10
